Delete tasks for type
---
tags:
- Tasks
description: Delete all tasks for a task type in a project. Useful when
  tasks were created by mistake at project start.
parameters:
  - in: path
    name: project_id
    required: true
    schema:
      type: string
    format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c25
  - in: path
    name: task_type_id
    required: true
    schema:
      type: string
    format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c25
responses:
    204:
        description: All tasks for given task type and project deleted
