Get open tasks
---
tags:
- Tasks
description: Return tasks for open projects with optional filters and
  pagination. Includes statistics.
parameters:
  - in: query
    name: project_id
    required: false
    schema:
      type: string
      format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c250
    description: Filter tasks on given project ID
  - in: query
    name: task_status_id
    required: false
    schema:
      type: string
      format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c250
    description: Filter tasks on given task status ID
  - in: query
    name: task_type_id
    required: false
    schema:
      type: string
      format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c250
    description: Filter tasks on given task type ID
  - in: query
    name: person_id
    required: false
    schema:
      type: string
      format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c250
    description: Filter tasks on given person ID
  - in: query
    name: start_date
    required: false
    schema:
      type: string
      format: date
    example: "2022-07-12"
    description: Filter tasks posterior to given start date
  - in: query
    name: due_date
    required: false
    schema:
      type: string
      format: date
    example: "2022-07-12"
    description: Filter tasks anterior to given due date
  - in: query
    name: priority
    required: false
    schema:
      type: integer
    example: 3
    description: Filter tasks on given priority
  - in: query
    name: page
    required: false
    schema:
      type: integer
      default: 1
    example: 1
    description: Page number
  - in: query
    name: limit
    required: false
    schema:
      type: integer
      default: 100
    example: 100
    description: Number of tasks per page

responses:
    200:
      description: List of tasks with pagination and statistics
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                description: List of tasks
              stats:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of tasks
                  total_duration:
                    type: integer
                    description: Total duration of tasks in minutes
                  total_estimation:
                    type: integer
                    description: Total estimation of tasks in minutes
                  status:
                    type: object
                    description: Number of tasks per status
              limit:
                type: integer
                description: Number of tasks per page
              page:
                type: integer
                description: Page number
              is_more:
                type: boolean
                description: True if there are more tasks to retrieve
    400:
      description: Bad request
