Set tasks priority
---
tags:
- Tasks
description: Set the priority of every task given in the id list.
  Tasks the current user is not allowed to update are skipped.
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        required:
          - task_ids
          - priority
        properties:
          task_ids:
            type: array
            items:
              type: string
              format: uuid
            example: [
              "a24a6ea4-ce75-4665-a070-57453082c250",
              "b24a6ea4-ce75-4665-a070-57453082c250"
            ]
          priority:
            type: integer
            example: 2
responses:
    200:
        description: Updated tasks
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
