Delete comment
---
tags:
- Tasks
description: Delete a comment by id for a task.
parameters:
  - in: path
    name: task_id
    required: true
    schema:
      type: string
      format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c25
  - in: path
    name: comment_id
    required: true
    schema:
      type: string
      format: uuid
    example: a24a6ea4-ce75-4665-a070-57453082c25
responses:
    204:
      description: Comment deleted
