from zou.app.utils.api import create_blueprint_for_api

from .resources import (
    AllProjectsResource,
    OpenProjectsResource,
    ProductionTeamResource,
    ProductionTeamRemoveResource,
    ProductionAssetTypeResource,
    ProductionAssetTypeRemoveResource,
    ProductionTaskTypeResource,
    ProductionTaskTypeRemoveResource,
    ProductionTaskTypesResource,
    ProductionTaskStatusResource,
    ProductionTaskStatusRemoveResource,
    ProductionStatusAutomationResource,
    ProductionStatusAutomationRemoveResource,
    ProductionMetadataDescriptorResource,
    ProductionMetadataDescriptorsResource,
    ProductionMilestonesResource,
    ProductionScheduleItemsResource,
    ProductionTaskTypeScheduleItemsResource,
    ProductionAssetTypesScheduleItemsResource,
    ProductionEpisodesScheduleItemsResource,
    ProductionSequencesScheduleItemsResource,
    ProductionTimeSpentsResource,
)

routes = [
    ("/data/projects/open", OpenProjectsResource),
    ("/data/projects/all", AllProjectsResource),
    ("/data/projects/<uuid:project_id>/team", ProductionTeamResource),
    (
        "/data/projects/<uuid:project_id>/task-types",
        ProductionTaskTypesResource,
    ),
    (
        "/data/projects/<uuid:project_id>/team/<uuid:person_id>",
        ProductionTeamRemoveResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/asset-types",
        ProductionAssetTypeResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/asset-types/<uuid:asset_type_id>",
        ProductionAssetTypeRemoveResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/task-types",
        ProductionTaskTypeResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/task-types/<uuid:task_type_id>",
        ProductionTaskTypeRemoveResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/task-status",
        ProductionTaskStatusResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/task-status/<uuid:task_status_id>",
        ProductionTaskStatusRemoveResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/status-automations",
        ProductionStatusAutomationResource,
    ),
    (
        "/data/projects/<uuid:project_id>/settings/status-automations/<uuid:status_automation_id>",
        ProductionStatusAutomationRemoveResource,
    ),
    (
        "/data/projects/<uuid:project_id>/metadata-descriptors",
        ProductionMetadataDescriptorsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/metadata-descriptors/<uuid:descriptor_id>",
        ProductionMetadataDescriptorResource,
    ),
    (
        "/data/projects/<uuid:project_id>/milestones",
        ProductionMilestonesResource,
    ),
    (
        "/data/projects/<uuid:project_id>/schedule-items",
        ProductionScheduleItemsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/schedule-items/task-types",
        ProductionTaskTypeScheduleItemsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/schedule-items/<uuid:task_type_id>/asset-types",
        ProductionAssetTypesScheduleItemsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/schedule-items/<uuid:task_type_id>/episodes",
        ProductionEpisodesScheduleItemsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/schedule-items/<uuid:task_type_id>/sequences",
        ProductionSequencesScheduleItemsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/time-spents",
        ProductionTimeSpentsResource,
    ),
]

blueprint = create_blueprint_for_api("projects", routes)
