"""Add Comment.api_token_id

Revision ID: 171d38257216
Revises: 61620680445d
Create Date: 2023-10-30 20:34:07.505275

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = "171d38257216"
down_revision = "61620680445d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "api_token_id",
                sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                default=uuid.uuid4,
                nullable=True,
            )
        )
        batch_op.alter_column(
            "person_id", existing_type=sa.UUID(), nullable=True
        )
        batch_op.create_index(
            batch_op.f("ix_comment_api_token_id"),
            ["api_token_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            None, "api_token", ["api_token_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comment_api_token_id"))
        batch_op.alter_column(
            "person_id", existing_type=sa.UUID(), nullable=False
        )
        batch_op.drop_column("api_token_id")

    # ### end Alembic commands ###
