"""Add day_off new columns

Revision ID: 9b85c14fa8a7
Revises: 45dafbb3f4e1
Create Date: 2024-02-23 14:48:48.461237

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b85c14fa8a7"
down_revision = "17ef8f7be758"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("day_off", schema=None) as batch_op:
        batch_op.add_column(sa.Column("end_date", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column("description", sa.String(), nullable=True)
        )
        batch_op.create_check_constraint(
            "day_off_date_check", "end_date IS NULL OR date < end_date"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("day_off", schema=None) as batch_op:
        batch_op.drop_constraint("day_off_date_check", type_="check")
        batch_op.drop_column("description")
        batch_op.drop_column("end_date")

    # ### end Alembic commands ###
