"""Add import workflow support for assets

Revision ID: a1b2c3d4e5f6
Revises: 20a8ad264659
Create Date: 2025-01-27 00:00:00.000000

This migration adds support for the import workflow feature which allows
asset types to have a simplified workflow for imported/purchased assets.

Changes:
1. Creates task_type_asset_type_import_link table for the many-to-many
   relationship between asset types and their import workflow task types.
2. Adds uses_import_workflow boolean column to the entity table to mark
   which assets should use the import workflow.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType


# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "20a8ad264659"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the association table for import task types
    op.create_table(
        "task_type_asset_type_import_link",
        sa.Column(
            "asset_type_id",
            UUIDType(binary=False),
            sa.ForeignKey("entity_type.id"),
            nullable=False,
            index=True,
            primary_key=True,
        ),
        sa.Column(
            "task_type_id",
            UUIDType(binary=False),
            sa.ForeignKey("task_type.id"),
            nullable=False,
            index=True,
            primary_key=True,
        ),
        sa.UniqueConstraint(
            "asset_type_id",
            "task_type_id",
            name="task_type_asset_type_import_link_uc",
        ),
    )

    # Add indexes for the new table
    op.create_index(
        "ix_task_type_asset_type_import_link_asset_type_id",
        "task_type_asset_type_import_link",
        ["asset_type_id"],
        unique=False,
    )
    op.create_index(
        "ix_task_type_asset_type_import_link_task_type_id",
        "task_type_asset_type_import_link",
        ["task_type_id"],
        unique=False,
    )

    # Add uses_import_workflow column to entity table
    op.add_column(
        "entity",
        sa.Column(
            "uses_import_workflow",
            sa.Boolean(),
            nullable=True,
            default=False,
            index=True,
        ),
    )
    op.create_index(
        "ix_entity_uses_import_workflow",
        "entity",
        ["uses_import_workflow"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove index and column from entity table
    op.drop_index("ix_entity_uses_import_workflow", table_name="entity")
    op.drop_column("entity", "uses_import_workflow")

    # Remove indexes from import link table
    op.drop_index(
        "ix_task_type_asset_type_import_link_task_type_id",
        table_name="task_type_asset_type_import_link",
    )
    op.drop_index(
        "ix_task_type_asset_type_import_link_asset_type_id",
        table_name="task_type_asset_type_import_link",
    )

    # Drop the import link table
    op.drop_table("task_type_asset_type_import_link")

    # ### end Alembic commands ###
