"""add production style field

Revision ID: f0c6cbb61869
Revises: b97a71306fc8
Create Date: 2022-08-15 17:26:36.567656

"""
from alembic import op
from zou.app.models.project import PROJECT_STYLES
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "f0c6cbb61869"
down_revision = "b97a71306fc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "production_style",
            sqlalchemy_utils.types.choice.ChoiceType(PROJECT_STYLES),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "production_style")
    # ### end Alembic commands ###
