from zou.app.utils.api import create_blueprint_for_api

from .resources import (
    ShotResource,
    ShotsResource,
    AllShotsResource,
    ShotsAndTasksResource,
    ShotAssetsResource,
    ShotPreviewsResource,
    ShotTaskTypesResource,
    ShotTasksResource,
    ShotVersionsResource,
    SceneResource,
    ScenesResource,
    SceneAndTasksResource,
    SceneTasksResource,
    SceneTaskTypesResource,
    SceneShotsResource,
    RemoveShotFromSceneResource,
    ProjectShotsResource,
    ProjectScenesResource,
    ProjectSequencesResource,
    ProjectEpisodesResource,
    ProjectEpisodeStatsResource,
    ProjectEpisodeRetakeStatsResource,
    EpisodeResource,
    EpisodesResource,
    EpisodeShotsResource,
    EpisodeAndTasksResource,
    EpisodeSequencesResource,
    EpisodeTasksResource,
    EpisodeTaskTypesResource,
    SequenceResource,
    SequencesResource,
    SequenceShotsResource,
    SequenceAndTasksResource,
    SequenceScenesResource,
    SequenceTasksResource,
    SequenceTaskTypesResource,
    EpisodeShotTasksResource,
    EpisodeAssetTasksResource,
    SequenceShotTasksResource,
    ProjectQuotasResource,
)

routes = [
    ("/data/shots", AllShotsResource),
    ("/data/shots/all", ShotsResource),
    ("/data/shots/with-tasks", ShotsAndTasksResource),
    ("/data/shots/<uuid:shot_id>", ShotResource),
    ("/data/shots/<uuid:shot_id>/assets", ShotAssetsResource),
    ("/data/shots/<uuid:shot_id>/task-types", ShotTaskTypesResource),
    ("/data/shots/<uuid:shot_id>/tasks", ShotTasksResource),
    ("/data/shots/<uuid:shot_id>/preview-files", ShotPreviewsResource),
    ("/data/shots/<uuid:shot_id>/versions", ShotVersionsResource),
    ("/data/scenes/all", ScenesResource),
    ("/data/scenes/with-tasks", SceneAndTasksResource),
    ("/data/scenes/<uuid:scene_id>", SceneResource),
    ("/data/scenes/<uuid:scene_id>/tasks", SceneTasksResource),
    ("/data/scenes/<uuid:scene_id>/task-types", SceneTaskTypesResource),
    ("/data/scenes/<uuid:scene_id>/shots", SceneShotsResource),
    (
        "/data/scenes/<uuid:scene_id>/shots/<uuid:shot_id>",
        RemoveShotFromSceneResource,
    ),
    ("/data/episodes", EpisodesResource),
    ("/data/episodes/with-tasks", EpisodeAndTasksResource),
    ("/data/episodes/<uuid:episode_id>", EpisodeResource),
    ("/data/episodes/<uuid:episode_id>/shots", EpisodeShotsResource),
    ("/data/episodes/<uuid:episode_id>/sequences", EpisodeSequencesResource),
    ("/data/episodes/<uuid:episode_id>/tasks", EpisodeTasksResource),
    ("/data/episodes/<uuid:episode_id>/task-types", EpisodeTaskTypesResource),
    ("/data/episodes/<uuid:episode_id>/shot-tasks", EpisodeShotTasksResource),
    (
        "/data/episodes/<uuid:episode_id>/asset-tasks",
        EpisodeAssetTasksResource,
    ),
    ("/data/sequences", SequencesResource),
    ("/data/sequences/with-tasks", SequenceAndTasksResource),
    ("/data/sequences/<uuid:sequence_id>", SequenceResource),
    ("/data/sequences/<uuid:sequence_id>/shots", SequenceShotsResource),
    ("/data/sequences/<uuid:sequence_id>/scenes", SequenceScenesResource),
    ("/data/sequences/<uuid:sequence_id>/tasks", SequenceTasksResource),
    (
        "/data/sequences/<uuid:sequence_id>/task-types",
        SequenceTaskTypesResource,
    ),
    (
        "/data/sequences/<uuid:sequence_id>/shot-tasks",
        SequenceShotTasksResource,
    ),
    ("/data/projects/<uuid:project_id>/shots", ProjectShotsResource),
    ("/data/projects/<uuid:project_id>/scenes", ProjectScenesResource),
    ("/data/projects/<uuid:project_id>/sequences", ProjectSequencesResource),
    ("/data/projects/<uuid:project_id>/episodes", ProjectEpisodesResource),
    (
        "/data/projects/<uuid:project_id>/episodes/stats",
        ProjectEpisodeStatsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/episodes/retake-stats",
        ProjectEpisodeRetakeStatsResource,
    ),
    (
        "/data/projects/<uuid:project_id>/quotas/<uuid:task_type_id>",
        ProjectQuotasResource,
    ),
]


blueprint = create_blueprint_for_api("shots", routes)
