Get asset types schedule items
---
description: Retrieve asset types schedule items for given task type.
tags:
  - Projects
parameters:
  - in: query
    name: episode_id
    required: false
    schema:
      type: string
      format: uuid
    description: Restrict results to asset types of the given episode
  - in: path
    name: project_id
    required: true
    schema:
      type: string
      format: uuid
    description: Project unique identifier
    example: a24a6ea4-ce75-4665-a070-57453082c25
  - in: path
    name: task_type_id
    required: true
    schema:
      type: string
      format: uuid
    description: Task type unique identifier
    example: b35b7fb5-df86-5776-b181-68564193d36
responses:
  200:
    description: All asset types schedule items for given task type
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
