"""
Shared Alembic env.py used by every Zou plugin.

Zou owns this file (it lives under ``zou/app/utils/plugin_alembic_template/``)
and points alembic at it via ``script_location``. Plugins only need to ship a
``migrations/versions/`` directory with their revision files — they no longer
have to copy boilerplate env.py / script.py.mako / alembic.ini around.

The plugin path is passed in via ``alembic_cfg.attributes['plugin_path']`` by
``run_plugin_migrations`` (and friends) in ``zou/app/utils/plugins.py``.
"""

import importlib.util
import logging
import sys

from alembic import context
from logging.config import fileConfig
from pathlib import Path
from sqlalchemy import create_engine, pool

from zou.app import db
from zou.app.utils.plugins import PluginManifest


config = context.config

# The plugin path is injected by zou.app.utils.plugins.run_plugin_migrations.
# When env.py is invoked outside that flow (e.g. by hand) we fall back to a
# best-effort guess based on the script_location's parent directory so the
# old layout (env.py inside the plugin) keeps working.
plugin_path = Path(
    config.attributes.get("plugin_path")
    or Path(config.get_main_option("script_location")).resolve().parent
)
manifest = PluginManifest.from_plugin_path(plugin_path)

plugin_prefix = f"plugin_{manifest['id']}_"
module_name = f"_plugin_models_{manifest['id']}"

# Skip re-execution of models.py when the plugin's tables are already
# registered on db.metadata. The pre_install hook calls _import_plugin_module,
# which transitively imports models.py; without this guard alembic would try
# to redefine the same Table object and crash with
# "Table 'plugin_<id>_…' is already defined for this MetaData instance".
already_loaded = any(
    table.startswith(plugin_prefix) for table in db.metadata.tables
)
if not already_loaded:
    models_path = plugin_path / "models.py"
    if models_path.exists():
        spec = importlib.util.spec_from_file_location(
            module_name, models_path
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)


if config.config_file_name:
    fileConfig(config.config_file_name)
logger = logging.getLogger("alembic.env")


def include_object(object, name, type_, reflected, compare_to):
    """Restrict alembic to tables owned by this plugin."""
    if type_ == "table":
        return name.startswith(plugin_prefix)
    return True


def render_item(type_, obj, autogen_context):
    """Render UUIDType columns with the right import in autogenerated files."""
    import sqlalchemy_utils

    if type_ == "type" and isinstance(
        obj, sqlalchemy_utils.types.uuid.UUIDType
    ):
        autogen_context.imports.add("import sqlalchemy_utils")
        autogen_context.imports.add("import uuid")
        return (
            "sqlalchemy_utils.types.uuid.UUIDType(binary=False),"
            " default=uuid.uuid4"
        )
    return False


def run_migrations_online():
    url = config.get_main_option("sqlalchemy.url")
    connectable = create_engine(url, poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=db.metadata,
            version_table=f"alembic_version_{manifest['id']}",
            compare_type=True,
            include_object=include_object,
            render_item=render_item,
        )
        with context.begin_transaction():
            context.run_migrations()


run_migrations_online()
