name: Deploy Zou to staging environment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Update Zou on staging server
      uses: appleboy/ssh-action@v0.1.4
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USERNAME }}
       key: ${{ secrets.KEY }}
       port: ${{ secrets.PORT }}
       script_stop: true
       script: |
         cd /opt/zou
         source /etc/zou/zou.env
         sudo /opt/zou/zouenv/bin/pip install --upgrade git+https://github.com/cgwire/zou.git
         sudo -E -u zou /opt/zou/zouenv/bin/zou upgrade-db
         sudo systemctl restart zou zou-events zou-jobs
